language: python
python:
  - "2.7"
  - "3.5"
env:
  matrix:
    - TORNADO_VERSION=3.2
    - TORNADO_VERSION=4.4.2
    - TORNADO_VERSION=4.5.1
    - TORNADO_VERSION=5.0.2
install:
  - "pip install tornado==$TORNADO_VERSION"
  - "pip install nose"
script: nosetests
